<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Batters'-Data-Extraction" data-toc-modified-id="Batters'-Data-Extraction-1">Batters' Data Extraction</a></span></li><li><span><a href="#Bowlers'-Data-Extraction" data-toc-modified-id="Bowlers'-Data-Extraction-2">Bowlers' Data Extraction</a></span></li></ul></div>

In [89]:
import pandas as pd
from bs4 import BeautifulSoup
import requests

In [90]:
# load html

path = "C:\Users\aly98\Desktop\res DSMP\web scraping sellenium\psl project\Html extraction selenium\html_batting_bowling.html"

with open(rpath, 'r') as f:
    html = f.read()

In [91]:
soup = BeautifulSoup(html, 'html.parser')

In [115]:
cont = soup.find_all('div', class_='ds-rounded-lg ds-mt-2')
len(cont)

558

## Batters' Data Extraction

In [93]:
# for the batsman's data
batting_stats = {}

# container of each batting and bowling scores
cont = soup.find_all('div', class_='ds-rounded-lg ds-mt-2')

for i in range(int(len(cont)/2)):
    
    # team name
    team1 = cont[i*2].find('span', class_='ds-text-title-xs ds-font-bold ds-capitalize').text.strip()
    team2 = cont[i*2+1].find('span', class_='ds-text-title-xs ds-font-bold ds-capitalize').text.strip()
    
    # season detail
    season_table = soup.find_all('table', class_='ds-w-full ds-table ds-table-sm ds-table-auto')
    stadium = season_table[i].find('tbody').find_all('tr')[0].text.strip()
    
    season = None
    for k in range(4,9):
        if 'match' in season_table[i].find('tbody').find_all('tr')[k].find_all('td')[1].text.strip():
            season = season_table[i].find('tbody').find_all('tr')[k].find_all('td')[1].text.strip().split(' ')[2]
            break
    
    
    # team1 batting and team2 batting table
    table1 = cont[i*2].find_all('table')[0]
    table2 = cont[i*2+1].find_all('table')[0]
    
    all_table = [table1,table2]
    
    for table in all_table:
        
        # no of rows in a table
        n = len(table.find('tbody').find_all('tr', class_='')) - 2
        
        for j in range(n):
            
            cells = table.find('tbody').find_all('tr', class_='')[j].find_all('td')

            name = cells[0].text.strip()
            wicket_taken = cells[1].text.strip()
            total_runs = cells[2].text.strip()
            total_balls = cells[3].text.strip()
            fours = cells[5].text.strip()
            sixes = cells[6].text.strip()
            strike_rate = cells[7].text.strip()
            
            # batting team and bowling team
            current_team = team1 if table == all_table[0] else team2
            opposing_team = team2 if table == all_table[0] else team1

            if name in batting_stats:
                batting_stats[name]['total_runs'].append(total_runs)
                batting_stats[name]['total_balls'].append(total_balls)
                batting_stats[name]['wicket_taken'].append(wicket_taken)
                batting_stats[name]['fours'].append(fours)
                batting_stats[name]['sixes'].append(sixes)
                batting_stats[name]['strike_rate'].append(strike_rate)
                batting_stats[name]['team'].append(current_team)
                batting_stats[name]['opposing_team'].append(opposing_team)
                batting_stats[name]['season'].append(season)
                batting_stats[name]['stadium'].append(stadium)
                
            else:
                batting_stats[name] = {
                    
                    'total_runs':[total_runs],
                    'total_balls':[total_balls],
                    'wicket_taken':[wicket_taken],
                    'fours':[fours],
                    'sixes':[sixes],
                    'strike_rate':[strike_rate],
                    'team':[current_team],
                    'opposing_team':[opposing_team],
                    'season':[season],
                    'stadium':[stadium] 
                
                }
                
    print(f'Team {i} data extract')

Team 0 data extract
Team 1 data extract
Team 2 data extract
Team 3 data extract
Team 4 data extract
Team 5 data extract
Team 6 data extract
Team 7 data extract
Team 8 data extract
Team 9 data extract
Team 10 data extract
Team 11 data extract
Team 12 data extract
Team 13 data extract
Team 14 data extract
Team 15 data extract
Team 16 data extract
Team 17 data extract
Team 18 data extract
Team 19 data extract
Team 20 data extract
Team 21 data extract
Team 22 data extract
Team 23 data extract
Team 24 data extract
Team 25 data extract
Team 26 data extract
Team 27 data extract
Team 28 data extract
Team 29 data extract
Team 30 data extract
Team 31 data extract
Team 32 data extract
Team 33 data extract
Team 34 data extract
Team 35 data extract
Team 36 data extract
Team 37 data extract
Team 38 data extract
Team 39 data extract
Team 40 data extract
Team 41 data extract
Team 42 data extract
Team 43 data extract
Team 44 data extract
Team 45 data extract
Team 46 data extract
Team 47 data extract
Team 48 data extract
Team 49 data extract
Team 50 data extract
Team 51 data extract
Team 52 data extract
Team 53 data extract
Team 54 data extract
Team 55 data extract
Team 56 data extract
Team 57 data extract
Team 58 data extract
Team 59 data extract
Team 60 data extract
Team 61 data extract
Team 62 data extract
Team 63 data extract
Team 64 data extract
Team 65 data extract
Team 66 data extract
Team 67 data extract
Team 68 data extract
Team 69 data extract
Team 70 data extract
Team 71 data extract
Team 72 data extract
Team 73 data extract
Team 74 data extract
Team 75 data extract
Team 76 data extract
Team 77 data extract
Team 78 data extract
Team 79 data extract
Team 80 data extract
Team 81 data extract
Team 82 data extract
Team 83 data extract
Team 84 data extract
Team 85 data extract
Team 86 data extract
Team 87 data extract
Team 88 data extract
Team 89 data extract
Team 90 data extract
Team 91 data extract
Team 92 data extract
Team 93 data extract
Team 94 data extract
Team 95 data extract
Team 96 data extract
Team 97 data extract
Team 98 data extract
Team 99 data extract
Team 100 data extract
Team 101 data extract
Team 102 data extract
Team 103 data extract
Team 104 data extract
Team 105 data extract
Team 106 data extract
Team 107 data extract
Team 108 data extract
Team 109 data extract
Team 110 data extract
Team 111 data extract
Team 112 data extract
Team 113 data extract
Team 114 data extract
Team 115 data extract
Team 116 data extract
Team 117 data extract
Team 118 data extract
Team 119 data extract
Team 120 data extract
Team 121 data extract
Team 122 data extract
Team 123 data extract
Team 124 data extract
Team 125 data extract
Team 126 data extract
Team 127 data extract
Team 128 data extract
Team 129 data extract
Team 130 data extract
Team 131 data extract
Team 132 data extract
Team 133 data extract
Team 134 data extract
Team 135 data extract
Team 136 data extract
Team 137 data extract
Team 138 data extract
Team 139 data extract
Team 140 data extract
Team 141 data extract
Team 142 data extract
Team 143 data extract
Team 144 data extract
Team 145 data extract
Team 146 data extract
Team 147 data extract
Team 148 data extract
Team 149 data extract
Team 150 data extract
Team 151 data extract
Team 152 data extract
Team 153 data extract
Team 154 data extract
Team 155 data extract
Team 156 data extract
Team 157 data extract
Team 158 data extract
Team 159 data extract
Team 160 data extract
Team 161 data extract
Team 162 data extract
Team 163 data extract
Team 164 data extract
Team 165 data extract
Team 166 data extract
Team 167 data extract
Team 168 data extract
Team 169 data extract
Team 170 data extract
Team 171 data extract
Team 172 data extract
Team 173 data extract
Team 174 data extract
Team 175 data extract
Team 176 data extract
Team 177 data extract
Team 178 data extract
Team 179 data extract
Team 180 data extract
Team 181 data extract
Team 182 data extract
Team 183 data extract
Team 184 data extract
Team 185 data extract
Team 186 data extract
Team 187 data extract
Team 188 data extract
Team 189 data extract
Team 190 data extract
Team 191 data extract
Team 192 data extract
Team 193 data extract
Team 194 data extract
Team 195 data extract
Team 196 data extract
Team 197 data extract
Team 198 data extract
Team 199 data extract
Team 200 data extract
Team 201 data extract
Team 202 data extract
Team 203 data extract
Team 204 data extract
Team 205 data extract
Team 206 data extract
Team 207 data extract
Team 208 data extract
Team 209 data extract
Team 210 data extract
Team 211 data extract
Team 212 data extract
Team 213 data extract
Team 214 data extract
Team 215 data extract
Team 216 data extract
Team 217 data extract
Team 218 data extract
Team 219 data extract
Team 220 data extract
Team 221 data extract
Team 222 data extract
Team 223 data extract
Team 224 data extract
Team 225 data extract
Team 226 data extract
Team 227 data extract
Team 228 data extract
Team 229 data extract
Team 230 data extract
Team 231 data extract
Team 232 data extract
Team 233 data extract
Team 234 data extract
Team 235 data extract
Team 236 data extract
Team 237 data extract
Team 238 data extract
Team 239 data extract
Team 240 data extract
Team 241 data extract
Team 242 data extract
Team 243 data extract
Team 244 data extract
Team 245 data extract
Team 246 data extract
Team 247 data extract
Team 248 data extract
Team 249 data extract
Team 250 data extract
Team 251 data extract
Team 252 data extract
Team 253 data extract
Team 254 data extract
Team 255 data extract
Team 256 data extract
Team 257 data extract
Team 258 data extract
Team 259 data extract
Team 260 data extract
Team 261 data extract
Team 262 data extract
Team 263 data extract
Team 264 data extract
Team 265 data extract
Team 266 data extract
Team 267 data extract
Team 268 data extract
Team 269 data extract
Team 270 data extract
Team 271 data extract
Team 272 data extract
Team 273 data extract
Team 274 data extract
Team 275 data extract
Team 276 data extract
Team 277 data extract
Team 278 data extract

In [94]:
df = pd.DataFrame(columns = ['batsman','total_runs','total_balls','fours','sixes','strike_rate', 'wicket_taken', 'season', 'stadium', 'team', 'opposing_team'])

for key,value in batting_stats.items():
    
    df1 = pd.DataFrame(batting_stats[key])
    name = []
    for i in range(df1.shape[0]):
        name.append(key)
    df1.insert(0,'batsman',name)
    df = pd.concat([df,df1])

In [95]:
df.shape

(4483, 11)

In [96]:
df.shape

(4483, 11)

In [97]:
# 2020 season 19th match abondened after Multan Sultan only did bat and Karachi kings only field

# Define the data
data = {
    'batsman': [
        'Moeen Ali', 
        'Zeeshan Ashraf', 
        'Shan Masood (c)', 
        'Rilee Rossouw', 
        'Ravi Bopara', 
        'Khushdil Shah', 
        'Shahid Afridi', 
        'Sohail Tanvir'
    ],
    'total_runs': [29, 2, 9, 0, 4, 8, 35, 10],
    'total_balls': [22, 8, 17, 1, 2, 16, 17, 18],
    'fours': [2, 0, 0, 0, 1, 0, 1, 1],
    'sixes': [1, 0, 0, 0, 0, 0, 3, 0],
    'strike_rate': [131.81, 25.00, 52.94, 0.00, 200.00, 50.00, 205.88, 55.55],
    'wicket_taken': [
        'c Jordan b Aamer Yamin', 
        'c Jordan b Mohammad Amir', 
        'b Imad Wasim', 
        'c Walton b Aamer Yamin', 
        'c Walton b Imad Wasim', 
        'c Jordan b Umer Khan', 
        'not out', 
        'not out'
    ],
    'season': [2020] * 8,
    'stadium': ['Gaddafi Stadium, Lahore'] * 8,
    'team': ['Multan Sultans'] * 8,
    'opposing_team': ['Karachi Kings'] * 8
}

# Create the DataFrame
df1 = pd.DataFrame(data)

# Reorder columns as specified
df1 = df1[['batsman', 'total_runs', 'total_balls', 'fours', 'sixes', 'strike_rate', 'wicket_taken', 'season', 'stadium', 'team', 'opposing_team']]


# Display the DataFrame
df = pd.concat([df1,df])

In [98]:
# 2017 season 9th match Zalmi vs Gladiators, 9th Match at Sharjah incomplete match

# Data
data = {
    "batsman": [
        "Tamim Iqbal", 
        "Mohammad Hafeez", 
        "Kamran Akmal", 
        "Eoin Morgan", 
        "Sohaib Maqsood"
    ],
    "total_runs": [62, 16, 0, 1, 30],
    "total_balls": [46, 19, 3, 4, 24],
    "fours": [4, 2, 0, 0, 2],
    "sixes": [4, 0, 0, 0, 1],
    "strike_rate": [134.78, 84.21, 0.00, 25.00, 125.00],
    "wicket_taken": [
        'not out', 
        "c Hassan Khan b Mahmudullah", 
        "c Asad Shafiq b Hassan Khan", 
        "c Asad Shafiq b Rossouw", 
        'not out'
    ],
    "season": [2017] * 5,
    "stadium": ["Sharjah Cricket Stadium"] * 5,
    "team": ["Peshawar Zalmi"] * 5,
    "opposing_team": ["Quetta Gladiators"] * 5
}

# Create DataFrame
df2 = pd.DataFrame(data)

# Display DataFrame
df = pd.concat([df2,df])
df2

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
0,Tamim Iqbal,62,46,4,4,134.78,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,Mohammad Hafeez,16,19,2,0,84.21,c Hassan Khan b Mahmudullah,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,Kamran Akmal,0,3,0,0,0.00,c Asad Shafiq b Hassan Khan,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,Eoin Morgan,1,4,0,0,25.00,c Asad Shafiq b Rossouw,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,Sohaib Maqsood,30,24,2,1,125.00,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators

In [99]:
df.shape

(4496, 11)

In [100]:
df.to_csv('Batters_uncleaned_data.csv')

## Bowlers' Data Extraction

In [101]:
len(soup.find_all('div', class_='ds-rounded-lg ds-mt-2'))

558

In [102]:
# For Bowler's data
bowling_stats = {}

# container of each batting and bowling scores
cont = soup.find_all('div', class_='ds-rounded-lg ds-mt-2')

for i in range(int(len(cont)/2)):
    
    # team name
    team2 = cont[i*2].find('span', class_='ds-text-title-xs ds-font-bold ds-capitalize').text.strip()
    team1 = cont[i*2+1].find('span', class_='ds-text-title-xs ds-font-bold ds-capitalize').text.strip()
    
    # season detail
    season_table = soup.find_all('table', class_='ds-w-full ds-table ds-table-sm ds-table-auto')
    stadium = season_table[i].find('tbody').find_all('tr')[0].text.strip()
    season = None
    for k in range(4,9):
        if 'match' in season_table[i].find('tbody').find_all('tr')[k].find_all('td')[1].text.strip():
            season = season_table[i].find('tbody').find_all('tr')[k].find_all('td')[1].text.strip().split(' ')[2]
            break
    
    
    # team1 bowling and team2 bowling table
    table1 = cont[i*2].find_all('table')[1]
    table2 = cont[i*2+1].find_all('table')[1]
    
    all_table = [table1,table2]
    
    for table in all_table:
        
        # no of rows in a table
        n = len(table.find('tbody').find_all('tr', class_=''))
        
        for j in range(n):
            
            cells = table.find('tbody').find_all('tr', class_='')[j].find_all('td')

            name = cells[0].text.strip()
            overs = cells[1].text.strip()
            maiden = cells[2].text.strip()
            runs = cells[3].text.strip()
            wickets = cells[4].text.strip()
            economy = cells[5].text.strip()
            zeros = cells[6].text.strip()
            fours = cells[7].text.strip()
            sixes = cells[8].text.strip()
            wides = cells[9].text.strip()
            no_balls = cells[10].text.strip()
           
            
            # bowling team and batting team
            current_team = team1 if table == all_table[0] else team2
            opposing_team = team2 if table == all_table[0] else team1

            if name in bowling_stats:
                bowling_stats[name]['overs'].append(overs)
                bowling_stats[name]['maiden'].append(maiden)
                bowling_stats[name]['runs'].append(runs)
                bowling_stats[name]['wickets'].append(wickets)
                bowling_stats[name]['economy'].append(economy)
                bowling_stats[name]['zeros'].append(zeros)
                bowling_stats[name]['fours'].append(fours)
                bowling_stats[name]['sixes'].append(sixes)
                bowling_stats[name]['wides'].append(wides)
                bowling_stats[name]['no_balls'].append(no_balls)
                bowling_stats[name]['team'].append(current_team)
                bowling_stats[name]['opposing_team'].append(opposing_team)
                bowling_stats[name]['season'].append(season)
                bowling_stats[name]['stadium'].append(stadium)
                
                
                
            else:
                bowling_stats[name] = {
                    
                    'overs':[overs],
                    'maiden':[maiden],
                    'runs':[runs],
                    'wickets':[wickets],
                    'economy':[economy],
                    'zeros':[zeros],
                    'fours':[fours],
                    'sixes':[sixes],
                    'wides':[wides],
                    'no_balls':[no_balls],
                    'team':[current_team],
                    'opposing_team':[opposing_team],
                    'season':[season],
                    'stadium':[stadium]
                
                }
                
    print(f'bowlers Team {i} data extract')

bowlers Team 0 data extract
bowlers Team 1 data extract
bowlers Team 2 data extract
bowlers Team 3 data extract
bowlers Team 4 data extract
bowlers Team 5 data extract
bowlers Team 6 data extract
bowlers Team 7 data extract
bowlers Team 8 data extract
bowlers Team 9 data extract
bowlers Team 10 data extract
bowlers Team 11 data extract
bowlers Team 12 data extract
bowlers Team 13 data extract
bowlers Team 14 data extract
bowlers Team 15 data extract
bowlers Team 16 data extract
bowlers Team 17 data extract
bowlers Team 18 data extract
bowlers Team 19 data extract
bowlers Team 20 data extract
bowlers Team 21 data extract
bowlers Team 22 data extract
bowlers Team 23 data extract
bowlers Team 24 data extract
bowlers Team 25 data extract
bowlers Team 26 data extract
bowlers Team 27 data extract
bowlers Team 28 data extract
bowlers Team 29 data extract
bowlers Team 30 data extract
bowlers Team 31 data extract
bowlers Team 32 data extract
bowlers Team 33 data extract
bowlers Team 34 data extract
bowlers Team 35 data extract
bowlers Team 36 data extract
bowlers Team 37 data extract
bowlers Team 38 data extract
bowlers Team 39 data extract
bowlers Team 40 data extract
bowlers Team 41 data extract
bowlers Team 42 data extract
bowlers Team 43 data extract
bowlers Team 44 data extract
bowlers Team 45 data extract
bowlers Team 46 data extract
bowlers Team 47 data extract
bowlers Team 48 data extract
bowlers Team 49 data extract
bowlers Team 50 data extract
bowlers Team 51 data extract
bowlers Team 52 data extract
bowlers Team 53 data extract
bowlers Team 54 data extract
bowlers Team 55 data extract
bowlers Team 56 data extract
bowlers Team 57 data extract
bowlers Team 58 data extract
bowlers Team 59 data extract
bowlers Team 60 data extract
bowlers Team 61 data extract
bowlers Team 62 data extract
bowlers Team 63 data extract
bowlers Team 64 data extract
bowlers Team 65 data extract
bowlers Team 66 data extract
bowlers Team 67 data extract
bowlers Team 68 data extract
bowlers Team 69 data extract
bowlers Team 70 data extract
bowlers Team 71 data extract
bowlers Team 72 data extract
bowlers Team 73 data extract
bowlers Team 74 data extract
bowlers Team 75 data extract
bowlers Team 76 data extract
bowlers Team 77 data extract
bowlers Team 78 data extract
bowlers Team 79 data extract
bowlers Team 80 data extract
bowlers Team 81 data extract
bowlers Team 82 data extract
bowlers Team 83 data extract
bowlers Team 84 data extract
bowlers Team 85 data extract
bowlers Team 86 data extract
bowlers Team 87 data extract
bowlers Team 88 data extract
bowlers Team 89 data extract
bowlers Team 90 data extract
bowlers Team 91 data extract
bowlers Team 92 data extract
bowlers Team 93 data extract
bowlers Team 94 data extract
bowlers Team 95 data extract
bowlers Team 96 data extract
bowlers Team 97 data extract
bowlers Team 98 data extract
bowlers Team 99 data extract
bowlers Team 100 data extract
bowlers Team 101 data extract
bowlers Team 102 data extract
bowlers Team 103 data extract
bowlers Team 104 data extract
bowlers Team 105 data extract
bowlers Team 106 data extract
bowlers Team 107 data extract
bowlers Team 108 data extract
bowlers Team 109 data extract
bowlers Team 110 data extract
bowlers Team 111 data extract
bowlers Team 112 data extract
bowlers Team 113 data extract
bowlers Team 114 data extract
bowlers Team 115 data extract
bowlers Team 116 data extract
bowlers Team 117 data extract
bowlers Team 118 data extract
bowlers Team 119 data extract
bowlers Team 120 data extract
bowlers Team 121 data extract
bowlers Team 122 data extract
bowlers Team 123 data extract
bowlers Team 124 data extract
bowlers Team 125 data extract
bowlers Team 126 data extract
bowlers Team 127 data extract
bowlers Team 128 data extract
bowlers Team 129 data extract
bowlers Team 130 data extract
bowlers Team 131 data extract
bowlers Team 132 data extract
bowlers Team 133 data extract
bowlers Team 134 data extract
bowlers Team 135 data extract
bowlers Team 136 data extract
bowlers Team 137 data extract
bowlers Team 138 data extract
bowlers Team 139 data extract
bowlers Team 140 data extract
bowlers Team 141 data extract
bowlers Team 142 data extract
bowlers Team 143 data extract
bowlers Team 144 data extract
bowlers Team 145 data extract
bowlers Team 146 data extract
bowlers Team 147 data extract
bowlers Team 148 data extract
bowlers Team 149 data extract
bowlers Team 150 data extract
bowlers Team 151 data extract
bowlers Team 152 data extract
bowlers Team 153 data extract
bowlers Team 154 data extract
bowlers Team 155 data extract
bowlers Team 156 data extract
bowlers Team 157 data extract
bowlers Team 158 data extract
bowlers Team 159 data extract
bowlers Team 160 data extract
bowlers Team 161 data extract
bowlers Team 162 data extract
bowlers Team 163 data extract
bowlers Team 164 data extract
bowlers Team 165 data extract
bowlers Team 166 data extract
bowlers Team 167 data extract
bowlers Team 168 data extract
bowlers Team 169 data extract
bowlers Team 170 data extract
bowlers Team 171 data extract
bowlers Team 172 data extract
bowlers Team 173 data extract
bowlers Team 174 data extract
bowlers Team 175 data extract
bowlers Team 176 data extract
bowlers Team 177 data extract
bowlers Team 178 data extract
bowlers Team 179 data extract
bowlers Team 180 data extract
bowlers Team 181 data extract
bowlers Team 182 data extract
bowlers Team 183 data extract
bowlers Team 184 data extract
bowlers Team 185 data extract
bowlers Team 186 data extract
bowlers Team 187 data extract
bowlers Team 188 data extract
bowlers Team 189 data extract
bowlers Team 190 data extract
bowlers Team 191 data extract
bowlers Team 192 data extract
bowlers Team 193 data extract
bowlers Team 194 data extract
bowlers Team 195 data extract
bowlers Team 196 data extract
bowlers Team 197 data extract
bowlers Team 198 data extract
bowlers Team 199 data extract
bowlers Team 200 data extract
bowlers Team 201 data extract
bowlers Team 202 data extract
bowlers Team 203 data extract
bowlers Team 204 data extract
bowlers Team 205 data extract
bowlers Team 206 data extract
bowlers Team 207 data extract
bowlers Team 208 data extract
bowlers Team 209 data extract
bowlers Team 210 data extract
bowlers Team 211 data extract
bowlers Team 212 data extract
bowlers Team 213 data extract
bowlers Team 214 data extract
bowlers Team 215 data extract
bowlers Team 216 data extract
bowlers Team 217 data extract
bowlers Team 218 data extract
bowlers Team 219 data extract
bowlers Team 220 data extract
bowlers Team 221 data extract
bowlers Team 222 data extract
bowlers Team 223 data extract
bowlers Team 224 data extract
bowlers Team 225 data extract
bowlers Team 226 data extract
bowlers Team 227 data extract
bowlers Team 228 data extract
bowlers Team 229 data extract
bowlers Team 230 data extract
bowlers Team 231 data extract
bowlers Team 232 data extract
bowlers Team 233 data extract
bowlers Team 234 data extract
bowlers Team 235 data extract
bowlers Team 236 data extract
bowlers Team 237 data extract
bowlers Team 238 data extract
bowlers Team 239 data extract
bowlers Team 240 data extract
bowlers Team 241 data extract
bowlers Team 242 data extract
bowlers Team 243 data extract
bowlers Team 244 data extract
bowlers Team 245 data extract
bowlers Team 246 data extract
bowlers Team 247 data extract
bowlers Team 248 data extract
bowlers Team 249 data extract
bowlers Team 250 data extract
bowlers Team 251 data extract
bowlers Team 252 data extract
bowlers Team 253 data extract
bowlers Team 254 data extract
bowlers Team 255 data extract
bowlers Team 256 data extract
bowlers Team 257 data extract
bowlers Team 258 data extract
bowlers Team 259 data extract
bowlers Team 260 data extract
bowlers Team 261 data extract
bowlers Team 262 data extract
bowlers Team 263 data extract
bowlers Team 264 data extract
bowlers Team 265 data extract
bowlers Team 266 data extract
bowlers Team 267 data extract
bowlers Team 268 data extract
bowlers Team 269 data extract
bowlers Team 270 data extract
bowlers Team 271 data extract
bowlers Team 272 data extract
bowlers Team 273 data extract
bowlers Team 274 data extract
bowlers Team 275 data extract
bowlers Team 276 data extract

bowlers Team 277 data extract
bowlers Team 278 data extract

In [103]:
df2 = pd.DataFrame(columns = ['bowlers','overs', 'maiden', 'runs', 'wickets', 'economy', 'zeros', 'fours', 'sixes', 'wides', 'no_balls', 'season','stadium','team','opposing_team'])
for key,value in bowling_stats.items():
    df = pd.DataFrame(bowling_stats[key])
    
    name = []
    for i in range(df.shape[0]):
        name.append(key)
    
    df.insert(0,'bowlers',name)
    df2 = pd.concat([df2,df])

In [104]:
df2.sample(10)

,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
2,Dale Steyn,2,0,15,0,7.50,4,2,0,0,0,2020,Rawalpindi Cricket Stadium,Islamabad United,Peshawar Zalmi
29,David Wiese,2,0,24,0,12.00,2,4,0,0,0,2022,"Gaddafi Stadium, Lahore",Lahore Qalandars,Karachi Kings
0,Liam Dawson,4,0,20,3,5.00,13,1,1,1,0,2018,Sharjah Cricket Stadium,Peshawar Zalmi,Lahore Qalandars
28,Umaid Asif,3.3,0,41,0,11.71,4,2,3,0,0,2021,"National Stadium, Karachi",Peshawar Zalmi,Karachi Kings
0,David Wiese,3,0,33,0,11.00,4,3,2,0,0,2018,Dubai International Cricket Stadium,Karachi Kings,Quetta Gladiators
23,Rashid Khan,4,0,21,4,5.25,11,0,1,1,0,2023,Rawalpindi Cricket Stadium,Lahore Qalandars,Islamabad United
10,Zahid Mahmood,4,0,34,0,8.50,8,1,2,0,0,2024,"National Stadium, Karachi",Karachi Kings,Multan Sultans
4,Shahid Afridi,3,0,38,0,12.66,6,2,4,0,0,2016,Sharjah Cricket Stadium,Peshawar Zalmi,Islamabad United
5,Mohammad Amir,4,0,29,1,7.25,12,3,1,1,0,2016,Dubai International Cricket Stadium,Karachi Kings,Peshawar Zalmi
14,Shahid Afridi,4,0,26,0,6.50,8,1,1,0,0,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Karachi Kings

In [105]:
df2.shape

(3278, 15)

In [109]:
# 2020 season 19th match abondened after Multan Sultan only bat and Karachi kings only field

# Define the data
data = {
    'bowlers': [
        'Mohammad Amir', 
        'Aamer Yamin', 
        'Chris Jordan', 
        'Imad Wasim', 
        'Iftikhar Ahmed', 
        'Umer Khan', 
        'Mitchell McClenaghan'
    ],
    'overs': [2.5, 3, 1, 4, 2, 3, 1],
    'maiden': [0, 0, 0, 0, 0, 0, 0],
    'runs': [15, 17, 9, 14, 7, 22, 14],
    'wickets': [1, 2, 0, 2, 0, 1, 0],
    'economy': [5.29, 5.66, 9.00, 3.50, 3.50, 7.33, 14.00],
    'zeros': [10, 8, 2, 15, 7, 6, 2],
    'fours': [0, 2, 1, 1, 0, 1, 0],
    'sixes': [1, 0, 0, 0, 0, 1, 2],
    'wides': [0, 0, 0, 0, 0, 1, 0],
    'no_balls': [0, 0, 0, 0, 0, 0, 0],
    'season': [2020] * 7,
    'stadium': ['Gaddafi Stadium, Lahore'] * 7,
    'team': ['Karachi Kings'] * 7,
    'opposing_team': ['Multan Sultans'] * 7
}

# Create the DataFrame
df3 = pd.DataFrame(data)

# Reorder columns as specified
df3 = df3[['bowlers', 'overs', 'maiden', 'runs', 'wickets', 'economy', 'zeros', 'fours', 'sixes', 'wides', 'no_balls', 'season', 'stadium', 'team', 'opposing_team']]


df2 = pd.concat([df2,df3])

In [110]:
# 2017 season 9th match Zalmi vs Gladiators, 9th Match at Sharjah incomplete match

data = {
    "bowlers": [
        "Zulfiqar Babar", 
        "Mohammad Nawaz", 
        "Anwar Ali", 
        "Mahmudullah", 
        "Hassan Khan", 
        "Rilee Rossouw", 
        "Thisara Perera"
    ],
    "overs": [4, 3, 2, 3, 2, 1, 1],
    "maiden": [0, 0, 0, 0, 0, 0, 0],
    "runs": [37, 18, 22, 18, 8, 8, 4],
    "wickets": [0, 0, 0, 1, 1, 1, 0],
    "economy": [9.25, 6.00, 11.00, 6.00, 4.00, 8.00, 4.00],
    "zeros": [9, 10, 1, 7, 8, 3, 2],
    "fours": [2, 1, 2, 2, 1, 0, 0],
    "sixes": [2, 1, 1, 0, 0, 1, 0],
    "wides": [1, 0, 0, 0, 1, 0, 0],
    "no_balls": [0, 0, 0, 0, 0, 0, 0],
    "season": [2017] * 7,
    "stadium": ["Sharjah Cricket Stadium"] * 7,
    "team": ["Quetta Gladiators"] * 7,
    "opposing_team": ["Peshawar Zalmi"] * 7
}

# Create DataFrame
df4 = pd.DataFrame(data)

# Display DataFrame
df2 = pd.concat([df2,df4])
df4

,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
0,Zulfiqar Babar,4,0,37,0,9.25,9,2,2,1,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
1,Mohammad Nawaz,3,0,18,0,6.00,10,1,1,0,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
2,Anwar Ali,2,0,22,0,11.00,1,2,1,0,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
3,Mahmudullah,3,0,18,1,6.00,7,2,0,0,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4,Hassan Khan,2,0,8,1,4.00,8,1,0,1,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
5,Rilee Rossouw,1,0,8,1,8.00,3,0,1,0,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
6,Thisara Perera,1,0,4,0,4.00,2,0,0,0,0,2017,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi

In [111]:
df2.shape

(3292, 15)

In [114]:
df2.to_csv('Bowlers_uncleaned_data.csv')