<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Dirty-Data" data-toc-modified-id="Dirty-Data-1">Dirty Data</a></span></li><li><span><a href="#Messy-Data" data-toc-modified-id="Messy-Data-2">Messy Data</a></span><ul class="toc-item"><li><span><a href="#fill-missing-values" data-toc-modified-id="fill-missing-values-2.1">fill missing values</a></span></li><li><span><a href="#Fixing-data-type-of-columns" data-toc-modified-id="Fixing-data-type-of-columns-2.2">Fixing data type of columns</a></span></li><li><span><a href="#Data-cleaning-batsman-name" data-toc-modified-id="Data-cleaning-batsman-name-2.3">Data cleaning batsman name</a></span></li><li><span><a href="#Data-cleaning-wicket_taken-column" data-toc-modified-id="Data-cleaning-wicket_taken-column-2.4">Data cleaning wicket_taken column</a></span></li><li><span><a href="#Fixing-structure-of-data" data-toc-modified-id="Fixing-structure-of-data-2.5">Fixing structure of data</a></span><ul class="toc-item"><li><span><a href="#derived-column-from-wicket_taken" data-toc-modified-id="derived-column-from-wicket_taken-2.5.1">derived column from wicket_taken</a></span></li></ul></li></ul></li></ul></div>

In [18]:
import pandas as pd
import numpy as np

In [19]:
# load uncleaned data

df = pd.read_csv(r"C:\Users\aly98\Desktop\Portfolio project\psl project\Data Extraction BeautifulSoup\Batters_uncleaned_data.csv")

In [20]:
df

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
0,0,Tamim Iqbal,62,46,4,4,134.78,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,1,Mohammad Hafeez,16,19,2,0,84.21,c Hassan Khan b Mahmudullah,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,2,Kamran Akmal,0,3,0,0,0.0,c Asad Shafiq b Hassan Khan,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,3,Eoin Morgan,1,4,0,0,25.0,c Asad Shafiq b Rossouw,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,4,Sohaib Maqsood,30,24,2,1,125.0,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
...,...,...,...,...,...,...,...,...,...,...,...,...
4494,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4495,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4496,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4497,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4498,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

# Data Cleaning

## Dirty Data
**Issue with data quality**<br>
- `Batsman name`: **ï¿½** invalid characters `invalid`
- `Strike rate`: some rows contains **"-"** `invalid`
- `total_runs`: 4092 index contains **"-"** `invalid`
- `wicket_taken`: some rows contains **ï¿½** `invalid`
- `season`: missing value `completness`
- `Invalid types`:<br>
    - season: 2022.0 float
    - total_runs type object
    - total_balls type object
    - total_fours type object
    - total_sixes type object
    - strike_rate type object



## Messy Data
**Issue with structure of data**<br>
`Unnamed: 0`: extra column  
`wicket_taken`: wicket type and name of wicket taker together<br>
`derived column`: seperate column for whether a player is captain or not.

In [21]:
df

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
0,0,Tamim Iqbal,62,46,4,4,134.78,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,1,Mohammad Hafeez,16,19,2,0,84.21,c Hassan Khan b Mahmudullah,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,2,Kamran Akmal,0,3,0,0,0.0,c Asad Shafiq b Hassan Khan,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,3,Eoin Morgan,1,4,0,0,25.0,c Asad Shafiq b Rossouw,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,4,Sohaib Maqsood,30,24,2,1,125.0,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
...,...,...,...,...,...,...,...,...,...,...,...,...
4494,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4495,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4496,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4497,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4498,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

In [22]:
df.tail(10)

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
4489,1,Usman Tariq,0,2,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4490,2,Usman Tariq,1,1,0,0,100.00,not out,2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4491,0,Shai Hope,6,9,0,0,66.66,c Cox b Imad Wasim,2024.0,Rawalpindi Cricket Stadium,Lahore Qalandars,Islamabad United
4492,0,Mehran Mumtaz,0,1,0,0,0.00,b Hosein,2024.0,Rawalpindi Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4493,0,Laurie Evans ï¿½,12,13,2,0,92.30,c Powell b Aamer Jamal,2024.0,Rawalpindi Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4494,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4495,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4496,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4497,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4498,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

In [23]:
df.sample(10)

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
1778,4,Rilee Rossouw,15,16,1,0,93.75,c ï¿½Sangakkara b Usama Mir,2017.0,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
1601,38,Hasan Ali,6,8,0,0,75.00,not out,2024.0,Rawalpindi Cricket Stadium,Karachi Kings,Islamabad United
1263,1,Anwar Ali,3,3,0,0,100.00,c Zafar Gohar b Mendis,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
4161,18,Shaheen Shah Afridi (c),55,34,2,4,161.76,c Sohail Khan b Mohammad Amir,2024.0,"National Stadium, Karachi",Lahore Qalandars,Quetta Gladiators
1693,2,Daren Sammy (c),20,19,3,0,105.26,c Mohammad Sami b Rumman Raees,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Islamabad United
2428,5,Shaheen Shah Afridi,2,6,0,0,33.33,b Wahab Riaz,2019.0,"Sheikh Zayed Stadium, Abu Dhabi",Lahore Qalandars,Peshawar Zalmi
1272,10,Anwar Ali,20,24,2,0,83.33,c Iftikhar Ahmed b Jordan,2017.0,"Gaddafi Stadium, Lahore",Quetta Gladiators,Peshawar Zalmi
1909,35,Jason Roy,18,14,4,0,128.57,c ï¿½Hope b Jahandad Khan,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
2585,1,Sahibzada Farhan,6,16,0,0,37.50,c Narine b Sohail Khan,2018.0,Sharjah Cricket Stadium,Islamabad United,Lahore Qalandars
1445,66,Asif Ali,6,3,0,1,200.00,c Fakhar Zaman b Shaheen Shah Afridi,2024.0,"Gaddafi Stadium, Lahore",Peshawar Zalmi,Lahore Qalandars

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4499 entries, 0 to 4498
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     4499 non-null   int64
 1   batsman        4499 non-null   object
 2   total_runs     4499 non-null   object
 3   total_balls    4499 non-null   object
 4   fours          4499 non-null   object
 5   sixes          4499 non-null   object
 6   strike_rate    4499 non-null   object
 7   wicket_taken   4499 non-null   object
 8   season         4486 non-null   float64
 9   stadium        4499 non-null   object
 10  team           4499 non-null   object
 11  opposing_team  4499 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 421.9+ KB

### fill missing values

`season`: missing value `completness`

In [25]:
# Missing data

df[df.season.isnull()]

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
47,34,Shane Watson,7,6,1,0,116.66,run out (Umar Amin),NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
120,15,Umar Amin,38,33,3,2,115.15,c Sohail Tanvir b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
275,35,Ahmed Shehzad,58,51,6,1,113.72,not out,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
451,19,Sohaib Maqsood,20,20,3,0,100.00,c Rossouw b Bravo,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
783,43,Kamran Akmal ï¿½,21,15,3,1,140.00,b Mohammad Nawaz,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
857,26,Wahab Riaz,12,8,1,0,150.00,run out (Mohammad Nawaz/Bravo),NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1719,28,Daren Sammy (c),18,16,2,0,112.50,c Mohammad Nawaz b Bravo,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1762,9,Chris Jordan,0,0,0,0,-,not out,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1802,28,Rilee Rossouw,39,32,5,0,121.87,not out,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
2075,29,Kieron Pollard,7,12,1,0,58.33,c ï¿½Sarfaraz Ahmed b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
3057,11,Imam-ul-Haq,3,4,0,0,75.00,c Ahmed Shehzad b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
3090,7,Ahsan Ali,25,18,3,1,138.88,c Sammy b Wahab Riaz,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
3328,0,Nabi Gul,9,12,0,0,75.00,c Ahmed Shehzad b Fawad Ahmed,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators

In [26]:
# 2019 season final match (missing season)

df.season.fillna(2019, inplace=True)

C:\Users\aly98\AppData\Local\Temp\ipykernel_19028\3507119066.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.season.fillna(2019, inplace=True)

In [27]:
# Test
df[df.season.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Fixing data type of columns
- drop unnamed column
- `Invalid types`:<br>
    - season type float
    - total_runs type object
    - total_balls type object
    - total_fours type object
    - total_sixes type object
    - strike_rate type object
- `Strike rate`: some rows contains **-** `invalid`
- `total_runs`: 4092 index contains **-** `invalid`

In [28]:
df.season = df.season.astype(int)

In [29]:
# drop unnamed
df.drop(columns='Unnamed: 0', inplace=True)

In [30]:
# total_runs
# no record of azam khan(absent hurt) in index 4100 --> drop the row

df[df.total_runs=='-']

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
4100,Azam Khan ï¿½,-,-,-,-,-,absent hurt,2023,Rawalpindi Cricket Stadium,Islamabad United,Lahore Qalandars

In [31]:
df.drop(index=4100, axis=0, inplace=True)

In [32]:
df.total_runs = df.total_runs.astype(int)

In [33]:
# total_balls

df.total_balls = df.total_balls.astype(int)

In [34]:
# fours

df.fours = df.fours.astype(int)

In [35]:
# sixes

df.sixes = df.sixes.astype(int)

In [36]:
# Strike_rate

df[df['strike_rate'] == '-']

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
160,Babar Azam,0,0,0,0,-,run out (Shadab Khan),2020,Rawalpindi Cricket Stadium,Karachi Kings,Islamabad United
222,Andre Russell,0,0,0,0,-,not out,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
296,Kevin Pietersen,0,0,0,0,-,run out (Imad Wasim),2017,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
330,Mohammad Nawaz,0,0,0,0,-,not out,2019,Sharjah Cricket Stadium,Quetta Gladiators,Karachi Kings
516,Kevon Cooper,0,0,0,0,-,not out,2016,Dubai International Cricket Stadium,Lahore Qalandars,Islamabad United
...,...,...,...,...,...,...,...,...,...,...,...
4071,David Willey,0,0,0,0,-,not out,2022,"National Stadium, Karachi",Multan Sultans,Islamabad United
4147,Shaheen Shah Afridi (c),0,0,0,0,-,not out,2022,"Gaddafi Stadium, Lahore",Lahore Qalandars,Islamabad United
4162,Zaman Khan,0,0,0,0,-,not out,2022,"National Stadium, Karachi",Lahore Qalandars,Islamabad United
4212,Athar Mahmood,0,0,0,0,-,not out,2022,"Gaddafi Stadium, Lahore",Islamabad United,Lahore Qalandars
4233,Akeal Hosein,0,0,0,0,-,not out,2023,Multan Cricket Stadium,Multan Sultans,Lahore Qalandars

In [37]:
df.strike_rate = df.strike_rate.replace('-',0)

In [38]:
df.strike_rate = df.strike_rate.astype(float)

In [39]:
# Test
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4498 entries, 0 to 4498
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   batsman        4498 non-null   object
 1   total_runs     4498 non-null   int32
 2   total_balls    4498 non-null   int32
 3   fours          4498 non-null   int32
 4   sixes          4498 non-null   int32
 5   strike_rate    4498 non-null   float64
 6   wicket_taken   4498 non-null   object
 7   season         4498 non-null   int32
 8   stadium        4498 non-null   object
 9   team           4498 non-null   object
 10  opposing_team  4498 non-null   object
dtypes: float64(1), int32(5), object(5)
memory usage: 333.8+ KB

In [40]:
df.describe()

,total_runs,total_balls,fours,sixes,strike_rate,season
count,4498.000000,4498.000000,4498.000000,4498.000000,4498.000000,4498.000000
mean,18.871498,14.289017,1.713651,0.765007,109.345333,2020.249444
std,21.105597,13.210432,2.303577,1.320424,71.899617,2.492601
min,0.000000,0.000000,0.000000,0.000000,0.000000,2016.000000
25%,3.000000,4.000000,0.000000,0.000000,60.000000,2018.000000
50%,12.000000,10.000000,1.000000,0.000000,109.090000,2020.000000
75%,28.000000,21.000000,3.000000,1.000000,150.000000,2022.000000
max,145.000000,67.000000,20.000000,12.000000,600.000000,2024.000000

### Data cleaning batsman name
- `Batsman name`: **ï¿½** invalid characters `invalid`

In [41]:
# Code
df[df.batsman.str.contains('ï¿½')]

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
178,Sam Billings ï¿½,2,4,0,0,50.00,b Mohammad Nawaz,2016,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators
179,Sam Billings ï¿½,26,20,1,1,130.00,c Mohammad Asghar b Wahab Riaz,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
180,Sam Billings ï¿½,4,2,1,0,200.00,run out (Vince),2016,Dubai International Cricket Stadium,Islamabad United,Karachi Kings
181,Sam Billings ï¿½,47,23,5,3,204.34,not out,2023,"Gaddafi Stadium, Lahore",Lahore Qalandars,Peshawar Zalmi
182,Sam Billings ï¿½,33,23,5,0,143.47,c Zeeshan Zameer b Curran,2023,"Gaddafi Stadium, Lahore",Lahore Qalandars,Islamabad United
...,...,...,...,...,...,...,...,...,...,...,...
4485,Tim Seifert ï¿½,41,30,8,0,136.66,lbw b Aamer Jamal,2024,"National Stadium, Karachi",Karachi Kings,Peshawar Zalmi
4493,Laurie Evans ï¿½,12,13,2,0,92.30,c Powell b Aamer Jamal,2024,Rawalpindi Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4494,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4495,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4496,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024,"National Stadium, Karachi",Quetta Gladiators,Islamabad United

In [42]:
df.batsman = df.batsman.str.replace('ï¿½','').str.strip()

In [43]:
# Test
df[df.batsman.str.contains('ï¿½')]

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Data cleaning wicket_taken column
-  `wicket_taken`: some rows contains **ï¿½** `invalid`

In [44]:
df[df.wicket_taken.str.contains('ï¿½')]

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
20,Shane Watson,26,14,2,2,185.71,run out (Pollard/ï¿½Sangakkara),2017,Sharjah Cricket Stadium,Islamabad United,Karachi Kings
21,Shane Watson,30,22,1,2,136.36,run out (sub [CJ Jordan]/ï¿½Kamran Akmal),2017,Sharjah Cricket Stadium,Islamabad United,Peshawar Zalmi
26,Shane Watson,1,6,0,0,16.66,run out (ï¿½Mohammad Rizwan),2018,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
33,Shane Watson,37,25,6,1,148.00,c ï¿½Kamran Akmal b Umaid Asif,2018,Dubai International Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
50,Shane Watson,27,20,2,2,135.00,run out (Umaid Asif/ï¿½Walton),2020,"National Stadium, Karachi",Quetta Gladiators,Karachi Kings
...,...,...,...,...,...,...,...,...,...,...,...
4479,Tim Seifert,8,9,0,1,88.88,st ï¿½Azam Khan b Imad Wasim,2024,"National Stadium, Karachi",Karachi Kings,Islamabad United
4482,Tim Seifert,49,31,6,2,158.06,st ï¿½Sarfaraz Ahmed b Abrar Ahmed,2024,Rawalpindi Cricket Stadium,Karachi Kings,Quetta Gladiators
4484,Tim Seifert,36,33,2,0,109.09,run out (Sikandar Raza/ï¿½Hope),2024,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4496,Laurie Evans,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4497,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars

In [45]:
df.wicket_taken = df.wicket_taken.str.replace('ï¿½','').str.strip()

In [46]:
# Test
df[df.wicket_taken.str.contains('ï¿½')]

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Fixing structure of data

`derived column`: seperate column for whether a player is captain or not.<br>

In [47]:
# Make new column if a player is captain in that particular match. if yes = 1 and no = 0

df[df.batsman.str.contains("\(c\)")].head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
7,Shan Masood (c),9,17,0,0,52.94,b Imad Wasim,2020,"Gaddafi Stadium, Lahore",Multan Sultans,Karachi Kings
191,Misbah-ul-Haq (c),41,28,4,1,146.42,c Umar Gul b Anwar Ali,2016,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators
192,Misbah-ul-Haq (c),12,12,2,0,100.00,c Malan b Mohammad Asghar,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
193,Misbah-ul-Haq (c),4,6,0,0,66.66,c Shakib Al Hasan b Bopara,2016,Dubai International Cricket Stadium,Islamabad United,Karachi Kings
194,Misbah-ul-Haq (c),32,27,3,2,118.51,c Shahid Afridi b Wahab Riaz,2016,Sharjah Cricket Stadium,Islamabad United,Peshawar Zalmi

In [48]:
df.insert(6,'captain', 0)

In [49]:
df['captain'][df.batsman.str.contains("\(c\)")] = 1

C:\Users\aly98\AppData\Local\Temp\ipykernel_19028\2764364724.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df['captain'][df.batsman.str.contains("\(c\)")] = 1
C:\Users\aly98\AppData\Local\Temp\ipykernel_19028\2764364724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['captain'][df.batsman.str.contains("\(c\)")] = 1

In [50]:
# Fixing the batsman name

df.batsman = df.batsman.str.replace("(c)",'').str.strip()

In [51]:
# Test

df.head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_taken,season,stadium,team,opposing_team
0,Tamim Iqbal,62,46,4,4,134.78,0,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,Mohammad Hafeez,16,19,2,0,84.21,0,c Hassan Khan b Mahmudullah,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,Kamran Akmal,0,3,0,0,0.00,0,c Asad Shafiq b Hassan Khan,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,Eoin Morgan,1,4,0,0,25.00,0,c Asad Shafiq b Rossouw,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,Sohaib Maqsood,30,24,2,1,125.00,0,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators

In [52]:
df[df.batsman.str.contains("\(c\)")].head()

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, captain, wicket_taken, season, stadium, team, opposing_team]
Index: []

`wicket_taken`: wicket type and name of wicket taker together<br>

In [53]:
# add another column 1 for wicket type

df.insert(7,'wicket_type',np.nan)

In [54]:
df.head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken,season,stadium,team,opposing_team
0,Tamim Iqbal,62,46,4,4,134.78,0,NaN,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,Mohammad Hafeez,16,19,2,0,84.21,0,NaN,c Hassan Khan b Mahmudullah,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,Kamran Akmal,0,3,0,0,0.00,0,NaN,c Asad Shafiq b Hassan Khan,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,Eoin Morgan,1,4,0,0,25.00,0,NaN,c Asad Shafiq b Rossouw,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,Sohaib Maqsood,30,24,2,1,125.00,0,NaN,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators

In [55]:
pd.set_option('display.max_rows', 2000)

In [56]:
def fix_wicket_type(series):
    data = []
    if series[0] == 'b':
        data.append('bowled')
    elif series[0] == 'r':
        data.append('run out')
    elif series[0] == 'c':
        data.append('catch')
    elif series[0] == 'l':
        data.append('lbw')
    elif series[0] == 's':
        data.append('stumped')
    elif series[0] == 'h':
        data.append('hit wicket')
    elif series[0] == 'o':
        data.append('obstructing the field')
    else:
        data.append('not out')
    return data[0]

In [57]:
df.wicket_type = df.wicket_taken.apply(fix_wicket_type)

In [58]:
# Test

df.sample(5)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken,season,stadium,team,opposing_team
4421,Reeza Hendricks,79,54,7,3,146.29,0,not out,not out,2024,Multan Cricket Stadium,Multan Sultans,Karachi Kings
85,Sharjeel Khan,4,6,0,0,66.66,0,run out,run out (Imran Khan),2021,"Sheikh Zayed Stadium, Abu Dhabi",Karachi Kings,Multan Sultans
608,Shoaib Malik,48,28,2,3,171.42,1,run out,run out (Umar Akmal),2018,Dubai International Cricket Stadium,Multan Sultans,Lahore Qalandars
4102,Azam Khan,13,10,1,1,130.00,0,catch,c Willey b Usama Mir,2024,Multan Cricket Stadium,Islamabad United,Multan Sultans
3036,Haris Rauf,0,1,0,0,0.00,0,catch,c Shadab Khan b Waqas Maqsood,2022,"National Stadium, Karachi",Lahore Qalandars,Islamabad United

#### derived column from wicket_taken

In [59]:
# add column for wicket taker

df.insert(8,'wicket_taken_by',np.nan)

In [60]:
def fix_wicket_taken(s):
    data = []
    
    if 'not out' in s:
        data.append('not out')
    elif 'run out' in s:
        data.append('run out') 
    elif ' b ' in s or 'b ' in s:
        s = s[s.find(' b ')+2:].strip()
        s = s[1:].strip() if s[0:2] == 'b ' else s
        data.append(s)
    else:
        data.append(s)
    return data[0]

In [61]:
df['wicket_taken_by'] = df.wicket_taken.apply(fix_wicket_taken)

In [62]:
# Test

df.sample(5)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken_by,wicket_taken,season,stadium,team,opposing_team
4044,Abdullah Shafique,24,22,3,0,109.09,0,catch,Imran Tahir,c Khushdil Shah b Imran Tahir,2022,"National Stadium, Karachi",Lahore Qalandars,Multan Sultans
2321,Joe Denly,0,1,0,0,0.00,0,bowled,Mohammad Amir,b Mohammad Amir,2021,"National Stadium, Karachi",Lahore Qalandars,Karachi Kings
4298,Tom Curran,1,2,0,0,50.00,0,catch,Ihsanullah,c Mohammad Rizwan b Ihsanullah,2023,Multan Cricket Stadium,Islamabad United,Multan Sultans
1011,Iftikhar Ahmed,1,2,0,0,50.00,0,catch,Muhammad Musa,c Hussain Talat b Muhammad Musa,2019,"National Stadium, Karachi",Karachi Kings,Islamabad United
278,Ahmed Shehzad,11,9,2,0,122.22,0,catch,Imad Wasim,c Jordan b Imad Wasim,2020,"National Stadium, Karachi",Quetta Gladiators,Karachi Kings

In [63]:
df.drop(columns = 'wicket_taken', inplace=True)

In [64]:
# For better Column Name

df.rename(columns={
    'captain': 'match_captain',
    'wicket_taken_by': 'dismissed_by',
    'stadium': 'venue_name',
    'team': 'team_name',
}, inplace=True)

In [65]:
# Test

df.sample(10)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,match_captain,wicket_type,dismissed_by,season,venue_name,team_name,opposing_team
3429,Sohail Akhtar,8,9,1,0,88.88,1,lbw,Zafar Gohar,2020,"Gaddafi Stadium, Lahore",Lahore Qalandars,Islamabad United
183,Sam Billings,2,5,0,0,40.00,0,catch,Naveen-ul-Haq,2023,"Gaddafi Stadium, Lahore",Lahore Qalandars,Quetta Gladiators
1265,Anwar Ali,6,8,0,0,75.00,0,catch,Bravo,2016,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
426,Cameron Delport,62,44,5,2,140.90,0,bowled,Mohammad Hasnain,2020,"National Stadium, Karachi",Karachi Kings,Quetta Gladiators
268,Ahmed Shehzad,0,1,0,0,0.00,0,lbw,Hasan Ali,2019,Dubai International Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4120,Marchant de Lange,2,4,0,0,50.00,0,catch,Haris Rauf,2022,"Gaddafi Stadium, Lahore",Islamabad United,Lahore Qalandars
4182,Mohammad Haris,7,6,1,0,116.66,0,catch,Hosein,2024,"Gaddafi Stadium, Lahore",Peshawar Zalmi,Quetta Gladiators
2165,Aamer Yamin,20,10,1,2,200.00,0,catch,Faulkner,2022,"National Stadium, Karachi",Karachi Kings,Quetta Gladiators
289,Kevin Pietersen,34,21,6,0,161.90,0,catch,Bravo,2016,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
1021,Iftikhar Ahmed,4,6,0,0,66.66,0,catch,Haris Rauf,2020,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars

In [66]:
# export the data to csv file

df.to_csv('Batsman_performance_data.csv', index=False)