<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Dirty-Data" data-toc-modified-id="Dirty-Data-1">Dirty Data</a></span></li><li><span><a href="#Messy-Data" data-toc-modified-id="Messy-Data-2">Messy Data</a></span><ul class="toc-item"><li><span><a href="#fill-missing-values" data-toc-modified-id="fill-missing-values-2.1">fill missing values</a></span></li><li><span><a href="#Fixing-data-type-of-columns" data-toc-modified-id="Fixing-data-type-of-columns-2.2">Fixing data type of columns</a></span></li><li><span><a href="#Data-cleaning-batsman-name" data-toc-modified-id="Data-cleaning-batsman-name-2.3">Data cleaning batsman name</a></span></li><li><span><a href="#Data-cleaning-wicket_taken-column" data-toc-modified-id="Data-cleaning-wicket_taken-column-2.4">Data cleaning wicket_taken column</a></span></li><li><span><a href="#Fixing-structure-of-data" data-toc-modified-id="Fixing-structure-of-data-2.5">Fixing structure of data</a></span><ul class="toc-item"><li><span><a href="#derived-column-from-wicket_taken" data-toc-modified-id="derived-column-from-wicket_taken-2.5.1">derived column from wicket_taken</a></span></li></ul></li></ul></li></ul></div>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Batters_uncleaned_data.csv')

In [3]:
df

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
0,0,Tamim Iqbal,62,46,4,4,134.78,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,1,Mohammad Hafeez,16,19,2,0,84.21,c Hassan Khan b Mahmudullah,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,2,Kamran Akmal,0,3,0,0,0.0,c Asad Shafiq b Hassan Khan,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,3,Eoin Morgan,1,4,0,0,25.0,c Asad Shafiq b Rossouw,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,4,Sohaib Maqsood,30,24,2,1,125.0,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
...,...,...,...,...,...,...,...,...,...,...,...,...
4491,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4492,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4493,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4494,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4495,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

# Data Cleaning

## Dirty Data
**Issue with data quality**<br>
- `Batsman name`: **ï¿½** invalid characters `invalid`
- `Strike rate`: some rows contains **"-"** `invalid`
- `total_runs`: 4092 index contains **"-"** `invalid`
- `wicket_taken`: some rows contains **ï¿½** `invalid`
- `season`: missing value `completness`
- `Invalid types`:<br>
    - season: 2022.0 float
    - total_runs type object
    - total_balls type object
    - total_fours type object
    - total_sixes type object
    - strike_rate type object



## Messy Data
**Issue with structure of data**<br>
`Unnamed: 0`: extra column  
`wicket_taken`: wicket type and name of wicket taker together<br>
`derived column`: seperate column for whether a player is captain or not.

In [4]:
df

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
0,0,Tamim Iqbal,62,46,4,4,134.78,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,1,Mohammad Hafeez,16,19,2,0,84.21,c Hassan Khan b Mahmudullah,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,2,Kamran Akmal,0,3,0,0,0.0,c Asad Shafiq b Hassan Khan,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,3,Eoin Morgan,1,4,0,0,25.0,c Asad Shafiq b Rossouw,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,4,Sohaib Maqsood,30,24,2,1,125.0,not out,2017.0,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
...,...,...,...,...,...,...,...,...,...,...,...,...
4491,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4492,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4493,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4494,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4495,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

In [5]:
df.tail(10)

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
4486,1,Usman Tariq,0,2,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4487,2,Usman Tariq,1,1,0,0,100.00,not out,2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4488,0,Shai Hope,6,9,0,0,66.66,c Cox b Imad Wasim,2024.0,Rawalpindi Cricket Stadium,Lahore Qalandars,Islamabad United
4489,0,Mehran Mumtaz,0,1,0,0,0.00,b Hosein,2024.0,Rawalpindi Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4490,0,Laurie Evans ï¿½,12,13,2,0,92.30,c Powell b Aamer Jamal,2024.0,Rawalpindi Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4491,1,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4492,2,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024.0,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4493,3,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024.0,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4494,0,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024.0,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4495,0,Obed McCoy,0,1,0,0,0.00,not out,2024.0,"National Stadium, Karachi",Islamabad United,Quetta Gladiators

In [6]:
df.sample(10)

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
846,17,Wahab Riaz,28,14,4,1,200.00,not out,2018.0,"National Stadium, Karachi",Peshawar Zalmi,Islamabad United
1045,48,Iftikhar Ahmed,4,6,0,0,66.66,lbw b Shamsi,2023.0,Rawalpindi Cricket Stadium,Quetta Gladiators,Karachi Kings
3784,14,Mohammad Wasim,4,2,1,0,200.00,c Kohler-Cadmore b Salman Irshad,2024.0,"Gaddafi Stadium, Lahore",Quetta Gladiators,Peshawar Zalmi
954,25,Imad Wasim,1,3,0,0,33.33,c Babar Azam b Salman Irshad,2024.0,"Gaddafi Stadium, Lahore",Islamabad United,Peshawar Zalmi
3650,5,Saim Ayub,35,31,5,0,112.90,c Allen b Mohammad Irfan,2021.0,"Sheikh Zayed Stadium, Abu Dhabi",Quetta Gladiators,Peshawar Zalmi
812,3,Shahid Yousaf,16,11,3,0,145.45,run out (Cooper),2016.0,Sharjah Cricket Stadium,Peshawar Zalmi,Lahore Qalandars
1674,1,Eoin Morgan,80,57,8,3,140.35,not out,2017.0,Dubai International Cricket Stadium,Peshawar Zalmi,Karachi Kings
4063,22,Abdullah Shafique,11,10,0,1,110.00,c ï¿½Sarfaraz Ahmed b Hosein,2024.0,"Gaddafi Stadium, Lahore",Lahore Qalandars,Quetta Gladiators
922,27,Ravi Bopara,9,5,0,1,180.00,c Umaid Asif b Mohammad Amir,2020.0,Multan Cricket Stadium,Multan Sultans,Karachi Kings
2631,10,Salman Agha,3,6,0,0,50.00,c Shadab Khan b Faheem Ashraf,2019.0,"National Stadium, Karachi",Lahore Qalandars,Islamabad United

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4496 entries, 0 to 4495
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Unnamed: 0     4496 non-null   int64
 1   batsman        4496 non-null   object
 2   total_runs     4496 non-null   object
 3   total_balls    4496 non-null   object
 4   fours          4496 non-null   object
 5   sixes          4496 non-null   object
 6   strike_rate    4496 non-null   object
 7   wicket_taken   4496 non-null   object
 8   season         4483 non-null   float64
 9   stadium        4496 non-null   object
 10  team           4496 non-null   object
 11  opposing_team  4496 non-null   object
dtypes: float64(1), int64(1), object(10)
memory usage: 421.6+ KB

### fill missing values

`season`: missing value `completness`

In [8]:
# Missing data

df[df.season.isnull()]

,Unnamed: 0,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
47,34,Shane Watson,7,6,1,0,116.66,run out (Umar Amin),NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
120,15,Umar Amin,38,33,3,2,115.15,c Sohail Tanvir b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
274,35,Ahmed Shehzad,58,51,6,1,113.72,not out,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
450,19,Sohaib Maqsood,20,20,3,0,100.00,c Rossouw b Bravo,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
781,42,Kamran Akmal ï¿½,21,15,3,1,140.00,b Mohammad Nawaz,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
855,26,Wahab Riaz,12,8,1,0,150.00,run out (Mohammad Nawaz/Bravo),NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1717,28,Daren Sammy (c),18,16,2,0,112.50,c Mohammad Nawaz b Bravo,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1760,9,Chris Jordan,0,0,0,0,-,not out,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1800,28,Rilee Rossouw,39,32,5,0,121.87,not out,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
2073,29,Kieron Pollard,7,12,1,0,58.33,c ï¿½Sarfaraz Ahmed b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
3055,11,Imam-ul-Haq,3,4,0,0,75.00,c Ahmed Shehzad b Mohammad Hasnain,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
3088,7,Ahsan Ali,25,18,3,1,138.88,c Sammy b Wahab Riaz,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
3325,0,Nabi Gul,9,12,0,0,75.00,c Ahmed Shehzad b Fawad Ahmed,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators

In [9]:
# 2019 season final match (missing season)

df.season.fillna(2019, inplace=True)

In [10]:
# Test
df[df.season.isnull()]

Empty DataFrame
Columns: [Unnamed: 0, batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Fixing data type of columns
- drop unnamed column
- `Invalid types`:<br>
    - season type float
    - total_runs type object
    - total_balls type object
    - total_fours type object
    - total_sixes type object
    - strike_rate type object
- `Strike rate`: some rows contains **-** `invalid`
- `total_runs`: 4092 index contains **-** `invalid`

In [11]:
df.season = df.season.astype(int)

In [12]:
# drop unnamed
df.drop(columns='Unnamed: 0', inplace=True)

In [13]:
# total_runs
# no record of azam khan(absent hurt) in index 4097 --> drop the row

df[df.total_runs=='-']

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
4097,Azam Khan ï¿½,-,-,-,-,-,absent hurt,2023,Rawalpindi Cricket Stadium,Islamabad United,Lahore Qalandars

In [14]:
df.drop(index=4097, axis=0, inplace=True)

In [15]:
df.total_runs = df.total_runs.astype(int)

In [16]:
# total_balls

df.total_balls = df.total_balls.astype(int)

In [17]:
# fours

df.fours = df.fours.astype(int)

In [18]:
# sixes

df.sixes = df.sixes.astype(int)

In [19]:
# Strike_rate

df[df['strike_rate'] == '-']

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
160,Babar Azam,0,0,0,0,-,run out (Shadab Khan),2020,Rawalpindi Cricket Stadium,Karachi Kings,Islamabad United
221,Andre Russell,0,0,0,0,-,not out,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
295,Kevin Pietersen,0,0,0,0,-,run out (Imad Wasim),2017,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
329,Mohammad Nawaz,0,0,0,0,-,not out,2019,Sharjah Cricket Stadium,Quetta Gladiators,Karachi Kings
515,Kevon Cooper,0,0,0,0,-,not out,2016,Dubai International Cricket Stadium,Lahore Qalandars,Islamabad United
...,...,...,...,...,...,...,...,...,...,...,...
4068,David Willey,0,0,0,0,-,not out,2022,"National Stadium, Karachi",Multan Sultans,Islamabad United
4144,Shaheen Shah Afridi (c),0,0,0,0,-,not out,2022,"Gaddafi Stadium, Lahore",Lahore Qalandars,Islamabad United
4159,Zaman Khan,0,0,0,0,-,not out,2022,"National Stadium, Karachi",Lahore Qalandars,Islamabad United
4209,Athar Mahmood,0,0,0,0,-,not out,2022,"Gaddafi Stadium, Lahore",Islamabad United,Lahore Qalandars
4230,Akeal Hosein,0,0,0,0,-,not out,2023,Multan Cricket Stadium,Multan Sultans,Lahore Qalandars

In [20]:
df.strike_rate = df.strike_rate.replace('-',0)

In [21]:
df.strike_rate = df.strike_rate.astype(float)

In [22]:
# Test
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4495 entries, 0 to 4495
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   batsman        4495 non-null   object
 1   total_runs     4495 non-null   int32
 2   total_balls    4495 non-null   int32
 3   fours          4495 non-null   int32
 4   sixes          4495 non-null   int32
 5   strike_rate    4495 non-null   float64
 6   wicket_taken   4495 non-null   object
 7   season         4495 non-null   int32
 8   stadium        4495 non-null   object
 9   team           4495 non-null   object
 10  opposing_team  4495 non-null   object
dtypes: float64(1), int32(5), object(5)
memory usage: 333.6+ KB

In [23]:
df.describe()

,total_runs,total_balls,fours,sixes,strike_rate,season
count,4495.000000,4495.000000,4495.000000,4495.000000,4495.000000,4495.000000
mean,18.836040,14.269855,1.708788,0.763737,109.302345,2020.249833
std,21.064992,13.193366,2.295959,1.319220,71.890211,2.493179
min,0.000000,0.000000,0.000000,0.000000,0.000000,2016.000000
25%,3.000000,4.000000,0.000000,0.000000,60.000000,2018.000000
50%,12.000000,10.000000,1.000000,0.000000,109.090000,2020.000000
75%,28.000000,21.000000,3.000000,1.000000,150.000000,2022.000000
max,145.000000,67.000000,20.000000,12.000000,600.000000,2024.000000

### Data cleaning batsman name
- `Batsman name`: **ï¿½** invalid characters `invalid`

In [24]:
# Code
df[df.batsman.str.contains('ï¿½')]

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
177,Sam Billings ï¿½,2,4,0,0,50.00,b Mohammad Nawaz,2016,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators
178,Sam Billings ï¿½,26,20,1,1,130.00,c Mohammad Asghar b Wahab Riaz,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
179,Sam Billings ï¿½,4,2,1,0,200.00,run out (Vince),2016,Dubai International Cricket Stadium,Islamabad United,Karachi Kings
180,Sam Billings ï¿½,47,23,5,3,204.34,not out,2023,"Gaddafi Stadium, Lahore",Lahore Qalandars,Peshawar Zalmi
181,Sam Billings ï¿½,33,23,5,0,143.47,c Zeeshan Zameer b Curran,2023,"Gaddafi Stadium, Lahore",Lahore Qalandars,Islamabad United
...,...,...,...,...,...,...,...,...,...,...,...
4482,Tim Seifert ï¿½,41,30,8,0,136.66,lbw b Aamer Jamal,2024,"National Stadium, Karachi",Karachi Kings,Peshawar Zalmi
4490,Laurie Evans ï¿½,12,13,2,0,92.30,c Powell b Aamer Jamal,2024,Rawalpindi Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
4491,Laurie Evans ï¿½,7,4,1,0,175.00,c Mirza Baig b Shaheen Shah Afridi,2024,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
4492,Laurie Evans ï¿½,1,2,0,0,50.00,c Jordan b Abbas Afridi,2024,"National Stadium, Karachi",Quetta Gladiators,Multan Sultans
4493,Laurie Evans ï¿½,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024,"National Stadium, Karachi",Quetta Gladiators,Islamabad United

In [25]:
df.batsman = df.batsman.str.replace('ï¿½','').str.strip()

In [26]:
# Test
df[df.batsman.str.contains('ï¿½')]

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Data cleaning wicket_taken column
-  `wicket_taken`: some rows contains **ï¿½** `invalid`

In [27]:
df[df.wicket_taken.str.contains('ï¿½')]

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
20,Shane Watson,26,14,2,2,185.71,run out (Pollard/ï¿½Sangakkara),2017,Sharjah Cricket Stadium,Islamabad United,Karachi Kings
21,Shane Watson,30,22,1,2,136.36,run out (sub [CJ Jordan]/ï¿½Kamran Akmal),2017,Sharjah Cricket Stadium,Islamabad United,Peshawar Zalmi
26,Shane Watson,1,6,0,0,16.66,run out (ï¿½Mohammad Rizwan),2018,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
33,Shane Watson,37,25,6,1,148.00,c ï¿½Kamran Akmal b Umaid Asif,2018,Dubai International Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
50,Shane Watson,27,20,2,2,135.00,run out (Umaid Asif/ï¿½Walton),2020,"National Stadium, Karachi",Quetta Gladiators,Karachi Kings
...,...,...,...,...,...,...,...,...,...,...,...
4476,Tim Seifert,8,9,0,1,88.88,st ï¿½Azam Khan b Imad Wasim,2024,"National Stadium, Karachi",Karachi Kings,Islamabad United
4479,Tim Seifert,49,31,6,2,158.06,st ï¿½Sarfaraz Ahmed b Abrar Ahmed,2024,Rawalpindi Cricket Stadium,Karachi Kings,Quetta Gladiators
4481,Tim Seifert,36,33,2,0,109.09,run out (Sikandar Raza/ï¿½Hope),2024,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars
4493,Laurie Evans,0,1,0,0,0.00,run out (Faheem Ashraf/ï¿½Azam Khan),2024,"National Stadium, Karachi",Quetta Gladiators,Islamabad United
4494,Arafat Minhas,1,1,0,0,100.00,run out (Sikandar Raza/ï¿½Hope),2024,"National Stadium, Karachi",Karachi Kings,Lahore Qalandars

In [28]:
df.wicket_taken = df.wicket_taken.str.replace('ï¿½','').str.strip()

In [29]:
# Test
df[df.wicket_taken.str.contains('ï¿½')]

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, wicket_taken, season, stadium, team, opposing_team]
Index: []

### Fixing structure of data

`derived column`: seperate column for whether a player is captain or not.<br>

In [30]:
# Make new column if a player is captain in that particular match. if yes = 1 and no = 0

df[df.batsman.str.contains("\(c\)")].head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,wicket_taken,season,stadium,team,opposing_team
7,Shan Masood (c),9,17,0,0,52.94,b Imad Wasim,2020,"Gaddafi Stadium, Lahore",Multan Sultans,Karachi Kings
190,Misbah-ul-Haq (c),41,28,4,1,146.42,c Umar Gul b Anwar Ali,2016,Dubai International Cricket Stadium,Islamabad United,Quetta Gladiators
191,Misbah-ul-Haq (c),12,12,2,0,100.00,c Malan b Mohammad Asghar,2016,Dubai International Cricket Stadium,Islamabad United,Peshawar Zalmi
192,Misbah-ul-Haq (c),4,6,0,0,66.66,c Shakib Al Hasan b Bopara,2016,Dubai International Cricket Stadium,Islamabad United,Karachi Kings
193,Misbah-ul-Haq (c),32,27,3,2,118.51,c Shahid Afridi b Wahab Riaz,2016,Sharjah Cricket Stadium,Islamabad United,Peshawar Zalmi

In [31]:
df.insert(6,'captain', 0)

In [32]:
df['captain'][df.batsman.str.contains("\(c\)")] = 1

C:\Users\aly98\AppData\Local\Temp\ipykernel_75580\2764364724.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['captain'][df.batsman.str.contains("\(c\)")] = 1

In [33]:
# Fixing the batsman name

df.batsman = df.batsman.str.replace("(c)",'').str.strip()

In [34]:
# Test

df.head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_taken,season,stadium,team,opposing_team
0,Tamim Iqbal,62,46,4,4,134.78,0,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,Mohammad Hafeez,16,19,2,0,84.21,0,c Hassan Khan b Mahmudullah,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,Kamran Akmal,0,3,0,0,0.00,0,c Asad Shafiq b Hassan Khan,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,Eoin Morgan,1,4,0,0,25.00,0,c Asad Shafiq b Rossouw,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,Sohaib Maqsood,30,24,2,1,125.00,0,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators

In [35]:
df[df.batsman.str.contains("\(c\)")].head()

Empty DataFrame
Columns: [batsman, total_runs, total_balls, fours, sixes, strike_rate, captain, wicket_taken, season, stadium, team, opposing_team]
Index: []

`wicket_taken`: wicket type and name of wicket taker together<br>

In [36]:
# add another column 1 for wicket type

df.insert(7,'wicket_type',np.nan)

In [37]:
df.head()

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken,season,stadium,team,opposing_team
0,Tamim Iqbal,62,46,4,4,134.78,0,NaN,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
1,Mohammad Hafeez,16,19,2,0,84.21,0,NaN,c Hassan Khan b Mahmudullah,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
2,Kamran Akmal,0,3,0,0,0.00,0,NaN,c Asad Shafiq b Hassan Khan,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
3,Eoin Morgan,1,4,0,0,25.00,0,NaN,c Asad Shafiq b Rossouw,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators
4,Sohaib Maqsood,30,24,2,1,125.00,0,NaN,not out,2017,Sharjah Cricket Stadium,Peshawar Zalmi,Quetta Gladiators

In [38]:
pd.set_option('display.max_rows', 2000)

In [39]:
def fix_wicket_type(series):
    data = []
    if series[0] == 'b':
        data.append('bowled')
    elif series[0] == 'r':
        data.append('run out')
    elif series[0] == 'c':
        data.append('catch')
    elif series[0] == 'l':
        data.append('lbw')
    elif series[0] == 's':
        data.append('stumped')
    elif series[0] == 'h':
        data.append('hit wicket')
    elif series[0] == 'o':
        data.append('obstructing the field')
    else:
        data.append('not out')
    return data[0]

In [40]:
df.wicket_type = df.wicket_taken.apply(fix_wicket_type)

In [41]:
# Test

df.sample(5)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken,season,stadium,team,opposing_team
1673,Eoin Morgan,1,3,0,0,33.33,0,bowled,b Saeed Ajmal,2017,Dubai International Cricket Stadium,Peshawar Zalmi,Islamabad United
379,Chris Gayle,11,9,0,1,122.22,0,catch,c Morgan b Iftikhar Ahmed,2017,Sharjah Cricket Stadium,Karachi Kings,Peshawar Zalmi
986,Sohail Tanvir,3,5,0,0,60.00,0,bowled,b Wiese,2020,"National Stadium, Karachi",Multan Sultans,Lahore Qalandars
874,Junaid Khan,0,0,0,0,0.00,0,not out,not out,2019,Dubai International Cricket Stadium,Multan Sultans,Karachi Kings
1678,Haris Sohail,12,14,0,0,85.71,0,catch,c Haddin b Watson,2017,Dubai International Cricket Stadium,Peshawar Zalmi,Islamabad United

#### derived column from wicket_taken

In [42]:
# add column for wicket taker

df.insert(8,'wicket_taken_by',np.nan)

In [43]:
def fix_wicket_taken(s):
    data = []
    
    if 'not out' in s:
        data.append('not out')
    elif 'run out' in s:
        data.append('run out') 
    elif ' b ' in s or 'b ' in s:
        s = s[s.find(' b ')+2:].strip()
        s = s[1:].strip() if s[0:2] == 'b ' else s
        data.append(s)
    else:
        data.append(s)
    return data[0]

In [44]:
df['wicket_taken_by'] = df.wicket_taken.apply(fix_wicket_taken)

In [45]:
# Test

df.sample(5)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,captain,wicket_type,wicket_taken_by,wicket_taken,season,stadium,team,opposing_team
1602,Mohammad Asghar,0,2,0,0,0.00,0,bowled,Russell,b Russell,2016,Dubai International Cricket Stadium,Peshawar Zalmi,Islamabad United
1002,Iftikhar Ahmed,14,21,1,0,66.66,0,lbw,Emrit,lbw b Emrit,2017,"Gaddafi Stadium, Lahore",Peshawar Zalmi,Quetta Gladiators
4363,Azmatullah Omarzai,0,2,0,0,0.00,0,catch,Shaheen Shah Afridi,c Rashid Khan b Shaheen Shah Afridi,2023,Rawalpindi Cricket Stadium,Peshawar Zalmi,Lahore Qalandars
1866,Tymal Mills,0,1,0,0,0.00,0,lbw,Mohammad Irfan,lbw b Mohammad Irfan,2017,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
1610,Shoaib Malik,0,4,0,0,0.00,0,catch,Mohammad Irfan,c Haddin b Mohammad Irfan,2016,Dubai International Cricket Stadium,Karachi Kings,Islamabad United

In [46]:
df.drop(columns = 'wicket_taken', inplace=True)

In [47]:
# For better Column Name

df.rename(columns={
    'captain': 'match_captain',
    'wicket_taken_by': 'dismissed_by',
    'stadium': 'venue_name',
    'team': 'team_name',
}, inplace=True)

In [48]:
# Test

df.sample(10)

,batsman,total_runs,total_balls,fours,sixes,strike_rate,match_captain,wicket_type,dismissed_by,season,venue_name,team_name,opposing_team
1902,Jason Roy,37,18,6,1,205.55,0,bowled,Hunain Shah,2024,"Gaddafi Stadium, Lahore",Quetta Gladiators,Islamabad United
579,James Vince,37,25,8,0,148.00,0,lbw,Usman Tariq,2024,"National Stadium, Karachi",Karachi Kings,Quetta Gladiators
602,Shoaib Malik,27,25,2,1,108.00,1,catch,Zafar Gohar,2016,Sharjah Cricket Stadium,Karachi Kings,Lahore Qalandars
1102,Sarfaraz Ahmed,40,33,5,0,121.21,1,catch,Haris Rauf,2021,"National Stadium, Karachi",Quetta Gladiators,Lahore Qalandars
2948,Sikandar Raza,0,1,0,0,0.00,0,catch,Hasan Ali,2024,"Gaddafi Stadium, Lahore",Lahore Qalandars,Karachi Kings
3422,Sohail Akhtar,34,30,1,3,113.33,1,not out,not out,2020,"Gaddafi Stadium, Lahore",Lahore Qalandars,Multan Sultans
2712,Liam Dawson,13,18,1,0,72.22,0,bowled,Faulkner,2022,"Gaddafi Stadium, Lahore",Islamabad United,Quetta Gladiators
3223,Shadab Khan,14,12,1,0,116.66,1,catch,Imran Tahir,2020,Rawalpindi Cricket Stadium,Islamabad United,Multan Sultans
377,Chris Gayle,5,7,1,0,71.42,0,catch,Narine,2017,Sharjah Cricket Stadium,Karachi Kings,Lahore Qalandars
4457,Haseebullah Khan,37,18,4,2,205.55,0,bowled,Usama Mir,2024,Multan Cricket Stadium,Peshawar Zalmi,Multan Sultans

In [50]:
# export the data to csv file

df.to_csv('PSL_Batsman_Performance_data')