<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [113]:
import pandas as pd
import numpy as np

In [114]:
df = pd.read_csv(r'Bowlers_uncleaned_Data.csv')
df.head()

,Unnamed: 0,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
0,0,Anwar Ali,3.0,1,21,1,7.00,11,4,0,2,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Islamabad United
1,1,Anwar Ali,4.0,0,33,2,8.25,7,2,1,4,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
2,2,Anwar Ali,4.0,0,38,1,9.50,10,1,2,4,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
3,3,Anwar Ali,4.0,0,27,1,6.75,10,2,1,1,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
4,4,Anwar Ali,2.1,0,10,1,4.61,10,2,0,1,0,2016.0,Sharjah Cricket Stadium,Quetta Gladiators,Islamabad United

In [115]:
df.sample(10)

,Unnamed: 0,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
1847,4,Mustafizur Rahman,2.0,0,10,0,5.00,3,0,0,0,0,2018.0,Sharjah Cricket Stadium,Lahore Qalandars,Peshawar Zalmi
1996,44,Umaid Asif,3.2,0,33,1,9.90,8,2,3,0,0,2023.0,"Gaddafi Stadium, Lahore",Quetta Gladiators,Lahore Qalandars
814,26,Wahab Riaz,4.0,0,26,2,6.50,11,1,2,0,0,2018.0,Sharjah Cricket Stadium,Peshawar Zalmi,Karachi Kings
2125,23,Liam Dawson,3.0,0,21,1,7.00,6,0,1,0,0,2022.0,"Gaddafi Stadium, Lahore",Islamabad United,Lahore Qalandars
19,19,Anwar Ali,3.4,0,37,0,10.09,10,4,2,3,0,2018.0,Sharjah Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
1281,10,Imran Khan,4.0,0,32,0,8.00,3,2,0,0,1,2022.0,"National Stadium, Karachi",Multan Sultans,Karachi Kings
3083,6,Akeal Hosein,4.0,0,30,1,7.50,12,5,0,2,0,2024.0,Multan Cricket Stadium,Quetta Gladiators,Multan Sultans
1569,57,Shadab Khan,4.0,0,25,3,6.25,8,1,1,1,0,2022.0,"Gaddafi Stadium, Lahore",Islamabad United,Quetta Gladiators
2056,15,Sameen Gul,3.0,0,13,2,4.33,11,1,0,2,0,2021.0,"Sheikh Zayed Stadium, Abu Dhabi",Peshawar Zalmi,Karachi Kings
2468,33,Mohammad Hasnain,4.0,0,57,0,14.25,3,4,4,2,0,2023.0,Rawalpindi Cricket Stadium,Quetta Gladiators,Peshawar Zalmi

In [116]:
# Extra column to drop

df.drop(columns = 'Unnamed: 0', inplace = True)

In [117]:
df.head()

,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
0,Anwar Ali,3.0,1,21,1,7.00,11,4,0,2,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Islamabad United
1,Anwar Ali,4.0,0,33,2,8.25,7,2,1,4,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Karachi Kings
2,Anwar Ali,4.0,0,38,1,9.50,10,1,2,4,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Peshawar Zalmi
3,Anwar Ali,4.0,0,27,1,6.75,10,2,1,1,0,2016.0,Dubai International Cricket Stadium,Quetta Gladiators,Lahore Qalandars
4,Anwar Ali,2.1,0,10,1,4.61,10,2,0,1,0,2016.0,Sharjah Cricket Stadium,Quetta Gladiators,Islamabad United

In [118]:
# check for duplicates
df.duplicated().sum()

0

In [135]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3292 entries, 0 to 3291
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   bowlers        3292 non-null   object
 1   overs          3292 non-null   float64
 2   total_balls    3292 non-null   int64
 3   maiden         3292 non-null   int64
 4   runs           3292 non-null   int64
 5   wickets        3292 non-null   int64
 6   economy        3292 non-null   float64
 7   zeros          3292 non-null   int64
 8   fours          3292 non-null   int64
 9   sixes          3292 non-null   int64
 10  wides          3292 non-null   int64
 11  no_balls       3292 non-null   int64
 12  season         3292 non-null   int32
 13  stadium        3292 non-null   object
 14  team           3292 non-null   object
 15  opposing_team  3292 non-null   object
dtypes: float64(2), int32(1), int64(9), object(4)
memory usage: 398.8+ KB

In [119]:
# checking for null values

df.isnull().sum()

bowlers           0
overs             0
maiden            0
runs              0
wickets           0
economy           0
zeros             0
fours             0
sixes             0
wides             0
no_balls          0
season           12
stadium           0
team              0
opposing_team     0
dtype: int64

In [120]:
# missing values in season

df[df.season.isnull()]

,bowlers,overs,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
135,Mohammad Nawaz,4.0,0,31,1,7.75,12,3,2,0,0,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
529,Sohail Tanvir,4.0,0,23,0,5.75,11,2,0,2,0,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
690,Dwayne Bravo,4.0,0,24,2,6.00,10,3,0,0,0,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
831,Wahab Riaz,4.0,0,19,1,4.75,11,1,0,2,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1224,Hasan Ali,4.0,0,29,0,7.25,8,4,0,0,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1333,Chris Jordan,3.0,0,38,0,12.66,5,4,2,1,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1413,Tymal Mills,4.0,0,31,0,7.75,9,5,0,1,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
1612,Kieron Pollard,1.0,0,5,0,5.00,1,0,0,0,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
2351,Fawad Ahmed,4.0,0,22,1,5.50,10,1,1,0,0,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
2441,Mohammad Hasnain,4.0,0,30,3,7.50,9,4,0,0,0,NaN,"National Stadium, Karachi",Quetta Gladiators,Peshawar Zalmi
2485,Sohaib Maqsood,1.0,0,8,0,8.00,2,1,0,0,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators
2486,Nabi Gul,0.5,0,4,0,4.80,1,0,0,0,0,NaN,"National Stadium, Karachi",Peshawar Zalmi,Quetta Gladiators

In [121]:
# the values is missing from the final match played in national karachi stadium in 2019 season

df.season.fillna(2019, inplace=True)

In [122]:
df.season = df.season.astype(int)

In [123]:
# for making a total balls column

def fix_balls(over):
    if len(str(over).split('.')) == 2:
        balls = (int(str(over).split('.')[0]) * 6) + (int(str(over).split('.')[1]))
        return balls
    else:
        balls = int(overs * 6)

In [124]:
total_balls = df.overs.apply(fix_balls)

df.insert(2,'total_balls',total_balls)

In [125]:
df.sample(5)

,bowlers,overs,total_balls,maiden,runs,wickets,economy,zeros,fours,sixes,wides,no_balls,season,stadium,team,opposing_team
1874,Faheem Ashraf,4.0,24,0,42,2,10.50,8,3,3,1,0,2020,"Gaddafi Stadium, Lahore",Islamabad United,Lahore Qalandars
307,Rumman Raees,3.0,18,0,19,1,6.33,7,2,0,0,1,2019,Dubai International Cricket Stadium,Islamabad United,Multan Sultans
838,Wahab Riaz,4.0,24,0,37,1,9.25,4,3,0,1,0,2020,Rawalpindi Cricket Stadium,Peshawar Zalmi,Islamabad United
3217,Mohammad Ali,4.0,24,0,23,3,5.75,15,3,1,0,0,2024,Multan Cricket Stadium,Multan Sultans,Karachi Kings
1102,Daren Sammy,2.0,12,0,21,0,10.50,2,1,1,3,0,2017,Dubai International Cricket Stadium,Peshawar Zalmi,Karachi Kings

In [126]:
df.shape

(3292, 16)

In [136]:
df.to_csv('Bowlers_performance_data',index=False)